<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <!-- Reference to Binding Internal project -->
  <ItemGroup>
    <ProjectReference Include="..\Internal\Emarsys.Binding.Internal.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Contains('android'))">
    <Compile Remove="**\iOS.cs" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.Contains('ios'))">
    <Compile Remove="**\Android.cs" />
  </ItemGroup>
  
  <!-- Package dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" />
  </ItemGroup>

  <!-- Target to inject release notes into .nuspec before pack -->
  <Target Name="InjectReleaseNotes" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <ChangelogContent>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../../CHANGELOG.md"))</ChangelogContent>
      <NuspecPath>$(MSBuildProjectDirectory)/Emarsys.Binding.nuspec</NuspecPath>
      <NuspecContent>$([System.IO.File]::ReadAllText("$(NuspecPath)"))</NuspecContent>
      <!-- Replace $releaseNotes$ token with actual content -->
      <UpdatedNuspecContent>$(NuspecContent.Replace("$releaseNotes$", "$(ChangelogContent)"))</UpdatedNuspecContent>
    </PropertyGroup>
    <WriteLinesToFile File="$(NuspecPath)" Lines="$(UpdatedNuspecContent)" Overwrite="true" />
  </Target>
</Project>
