name: Build NuGet Package
permissions:
  contents: read

on:
  workflow_call:
    outputs:
      version:
        description: "Package version"
        value: ${{ jobs.build-nuget-package.outputs.version }}
  workflow_dispatch:

jobs:
  build-nuget-package:
    name: Build and Pack NuGet Package
    runs-on: macos-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Import iOS Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}

      - name: Build iOS Native Framework
        run: |
          cd ios/native

          xcodebuild -project MauiEmarsys.xcodeproj -scheme MauiEmarsys -configuration Release -sdk iphoneos clean build ARCHS=arm64 ONLY_ACTIVE_ARCH=NO BUILD_DIR=./build
          xcodebuild -project MauiEmarsys.xcodeproj -scheme MauiEmarsys -configuration Release -sdk iphonesimulator clean build ARCHS="x86_64 arm64" ONLY_ACTIVE_ARCH=NO BUILD_DIR=./build

          rm -rf MauiEmarsysiOS.xcframework
          xcodebuild -create-xcframework \
            -framework build/Release-iphoneos/MauiEmarsys.framework \
            -framework build/Release-iphonesimulator/MauiEmarsys.framework \
            -output MauiEmarsysiOS.xcframework

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI
        run: |
          dotnet workload install maui

          # Install compatible iOS workload version for Xcode 16.4
          dotnet workload install ios --version 9.0.100

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clean and Restore Dependencies
        run: | 
          mkdir -p artifacts
          dotnet clean common/Public && dotnet restore common/Public 

      - name: Build and Pack NuGet package
        run: |
          rm -f artifacts/*.nupkg || true
          dotnet pack common/Public/ -p:NuspecFile=Emarsys.Binding.nuspec --configuration Release --output ./artifacts

      - name: Extract Version from nuspec
        id: get_version
        run: |
          VERSION=$(grep -o '<version>[^<]*</version>' common/Public/Emarsys.Binding.nuspec | sed 's/<version>\(.*\)<\/version>/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: artifacts/*.nupkg
          retention-days: 1
