name: Release Pipeline

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-ios-native:
    name: Build iOS Native Framework
    uses: ./.github/workflows/build-ios-native.yaml
    secrets: inherit

  build-nuget-package:
    name: Build NuGet Package
    needs: build-ios-native
    uses: ./.github/workflows/build-nuget-package.yaml
    secrets: inherit

  test-sample-apps:
    name: Build Sample Apps
    needs: build-nuget-package
    uses: ./.github/workflows/build-sample-apps.yaml
    secrets: inherit
    with:
      package-version: ${{ needs.build-nuget-package.outputs.version }}

  # publish-nuget:
  #   name: Publish to NuGet
  #   needs: [build-nuget-package, test-sample-apps]
  #   uses: ./.github/workflows/publish-nuget.yaml
  #   secrets: inherit
