name: Run Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dotnet:
    name: Run .NET Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET MAUI
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore test/

      - name: Run .NET Tests
        run: dotnet test test/

  test-ios:
    name: Run iOS Native Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Run iOS Tests
        run: |
          cd ios/native
          xcodebuild test \
            -project MauiEmarsys.xcodeproj \
            -scheme MauiEmarsysTests \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.2'

  test-android:
    name: Run Android Native Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Android Tests
        working-directory: android/native
        run: ./gradlew test
